development:
  adapter: mysql
  host: localhost
  database: "cd_dev"
  username: "cd"
  password: "9JauuqW5hDbh7aSj"
  encoding: "utf8"
  timeout: 5000
  reconnect: true

test:
  adapter: mysql
  database: "cd_test"
  username: "cd"
  password: "12345678"
  encoding: "utf8"
  timeout: 5000
  reconnect: true

production:
  adapter: mysql
  host: mysql01.cidadedemocratica.org.br
  database: "cidadedemocrat"
  username: "cidadedemocrat"
  password: "GAIDPY74"
  encoding: "utf8"
  timeout: 5000
  reconnect: true
